In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.layers import Dense
from keras.models import Sequential
import numpy as np


In [19]:
tran_ = np.genfromtxt('transfusion.csv', delimiter=',')
X=tran_[:,0:4]			# The dataset offers 4 input variables
Y=tran_[:,4]   			# Target variable with '1' and '0'
print(X)

[[  2.00000000e+00   5.00000000e+01   1.25000000e+04   9.80000000e+01]
 [  0.00000000e+00   1.30000000e+01   3.25000000e+03   2.80000000e+01]
 [  1.00000000e+00   1.60000000e+01   4.00000000e+03   3.50000000e+01]
 ..., 
 [  2.30000000e+01   3.00000000e+00   7.50000000e+02   6.20000000e+01]
 [  3.90000000e+01   1.00000000e+00   2.50000000e+02   3.90000000e+01]
 [  7.20000000e+01   1.00000000e+00   2.50000000e+02   7.20000000e+01]]


In [7]:
# Creating our first MLP model with Keras
mlp_keras = Sequential()    
mlp_keras.add(Dense(8, input_dim=4, init='uniform', activation='relu'))
mlp_keras.add(Dense(6, init='uniform', activation='relu'))


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, input_dim=4, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [8]:
mlp_keras.add(Dense(1, init='uniform', activation='sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [11]:
mlp_keras.compile(loss = 'binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [12]:
mlp_keras.fit(X,Y, nb_epoch=200, batch_size=8, verbose=0)

C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


In [13]:
accuracy = mlp_keras.evaluate(X,Y)
print("Accuracy : %.2f%% " %  (accuracy[1]*100 ))

 32/748 [>.............................] - ETA: 0sAccuracy : 79.68% 


In [14]:
# Using a different set of optimizer
from keras.optimizers import SGD
opt = SGD(lr=0.01)

In [15]:
# New model with different combinations of Optimizer and validation dataset as well
mlp_optim = Sequential()
mlp_optim.add(Dense(8, input_dim=4, init='uniform', activation='relu'))
mlp_optim.add(Dense(6, init='uniform', activation='relu'))
mlp_optim.add(Dense(1, init='uniform', activation='sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, input_dim=4, activation="relu", kernel_initializer="uniform")`
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [16]:
# Compiling the model with SGD
mlp_optim.compile(loss = 'binary_crossentropy', optimizer=opt,metrics=['accuracy'])

In [17]:
# Fitting the model and checking accuracy
mlp_optim.fit(X,Y, validation_split=0.3, nb_epoch=150, batch_size=10, verbose=0)
results_optim = mlp_optim.evaluate(X,Y)
print("Accuracy : %.2f%%" % (results_optim[1]*100 ) )

C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


 32/748 [>.............................] - ETA: 0sAccuracy : 76.20%
