In [1]:
import scipy
import numpy as np

In [2]:
from scipy import linalg
mat_ = np.array([[2,3,1], [4,9,10], [10,5,6]])           # Matrix Creation
print(mat_)

[[ 2  3  1]
 [ 4  9 10]
 [10  5  6]]


In [3]:
linalg.det(mat_)                 #Determinant of the matrix
inv_mat = linalg.inv(mat_)                  # Inverse of the matrix
print(inv_mat)

[[ 0.02409639 -0.07831325  0.12650602]
 [ 0.45783133  0.01204819 -0.09638554]
 [-0.42168675  0.12048193  0.03614458]]


In [4]:
# Singular Value Decomposition
comp_1, comp_2, comp_3 = linalg.svd(mat_)
print(comp_1)
print(comp_2)
print(comp_3)

[[-0.1854159   0.0294175  -0.98221971]
 [-0.73602677 -0.66641413  0.11898237]
 [-0.65106493  0.74500122  0.14521585]]
[ 18.34661713   5.73710697   1.57709968]
[[-0.53555313 -0.56881403 -0.62420625]
 [ 0.84418693 -0.38076134 -0.37731848]
 [-0.02304957 -0.72902085  0.6841033 ]]


In [5]:
# Scipy Stats module
from scipy import stats

# Generating a random sample of size 20 from normal distribution with mean 3 and standard deviation 5
rvs_20 = stats.norm.rvs(3,5 , size = 20)
print(rvs_20, '\n --- ')

# Computing the CDF of Beta distribution with a=100 and b=130 as shape parameters at random variable 0.41
cdf_ = scipy.stats.beta.cdf(0.41, a=100, b=130)
print(cdf_)

[  1.50889918  -0.52512335   7.42721059   5.12591525   3.94046958
  13.12785618   3.1895057   13.59008321  12.98736548  10.19862082
  11.71655729  -0.84468695   9.93834397   0.11804304   0.42097241
   7.08219115   9.20624758   4.5313581    1.87579898   6.22591561] 
 --- 
0.225009574362
